CREATE TABLE public.authors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    birthdate DATE NOT NULL,
    nationality VARCHAR(100) NOT NULL,
    registered_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    user_id INTEGER,
    CONSTRAINT uk_authors_first_name_last_name_birthdate_nationality
        UNIQUE (first_name, last_name, birthdate, nationality)
);

CREATE TABLE public.books_genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    genre VARCHAR(45) NOT NULL UNIQUE,
    registered_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    user_id INTEGER
);

CREATE TABLE public.books (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    isbn VARCHAR(20) NOT NULL UNIQUE,
    title VARCHAR(200) NOT NULL,
    publication_date DATE NOT NULL,
    genre_id INTEGER NOT NULL REFERENCES public.books_genres(id),
    registered_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    user_id INTEGER
);

CREATE TABLE public.books_authors (
    book_id INTEGER NOT NULL REFERENCES public.books(id),
    author_id INTEGER NOT NULL REFERENCES public.authors(id),
    PRIMARY KEY (book_id, author_id)
);
