CREATE TABLE public.client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    client_id VARCHAR(100) NOT NULL UNIQUE,
    client_secret VARCHAR(255) NOT NULL,
    redirect_uri VARCHAR(2048) NOT NULL,
    registered_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    revoked_at TIMESTAMP,
    revoked_by VARCHAR(100)
);

CREATE TABLE public.client_scopes (
    client_id BIGINT NOT NULL REFERENCES public.client(id),
    scope VARCHAR(100) NOT NULL,
    PRIMARY KEY (client_id, scope)
);

CREATE TABLE public.client_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES public.client(id),
    event VARCHAR(30) NOT NULL,
    performed_by VARCHAR(100) NOT NULL,
    performed_at TIMESTAMP NOT NULL,
    reason VARCHAR(500)
);

CREATE INDEX idx_client_audit_client_id
    ON public.client_audit (client_id);
